export default {
  products: [
    {
      _id: '1',
      name: 'WASHING DETURGENT',
      category: 'DETURGENT',
      image: '/img/1.jpg',
      price: 20,
      brand: ' SURF EXCEL',
      rating: 5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'WASHING DETURGENT',
      category: 'DETURGENT',
      image: '/img/2.jpg',
      price: 50,
      brand: ' SURF EXCEL',
      rating: 4.2,
      numReviews: 5
    },
    {
      _id: '3',
      name: 'WASHING DETURGENT',
      category: 'DETURGENT',
      image: '/img/3.jpg',
      price: 70,
      brand: ' RIN',
      rating: 4.9,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'WASHING DETURGENT',
      category: 'DETURGENT',
      image: '/img/4.jpg',
      price: 40,
      brand: ' ACTIVE',
      rating: 3,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '5',
      name: 'SOAP',
      category: 'BODY SOAP',
      image: '/img/5.jpg',
      price: 30,
      brand: ' LUX',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '6',
      name: 'SOAP',
      category: 'BODY SOAP',
      image: '/img/6.jpg',
      price: 45,
      brand: ' DETTOL',
      rating: 4.8,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '7',
      name: 'SOAP',
      category: 'BODY SOAP',
      image: '/img/7.jpg',
      price: 40,
      brand: ' DOVE',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '8',
      name: 'SOAP',
      category: 'BODY SOAP',
      image: '/img/8.jpg',
      price: 20,
      brand: ' NEUSTAR',
      rating: 4.0,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '9',
      name: 'SOAP',
      category: 'DETURGENT SOAP',
      image: '/img/9.jpg',
      price: 10,
      brand: ' GHADI',
      rating: 4.7,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '10',
      name: 'SOAP',
      category: 'BODY SOAP',
      image: '/img/10.jpg',
      price: 30,
      brand: ' PATANJALI',
      rating: 5.0,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '11',
      name: 'SOAP',
      category: 'DETURGENT SOAP',
      image: '/img/11.jpg',
      price: 35,
      brand: ' RIN',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '12',
      name: 'SOAP',
      category: 'DETURGENT SOAP',
      image: '/img/12.jpg',
      price: 35,
      brand: ' FENA',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '13',
      name: 'COOKING OIL',
      category: 'OIL',
      image: '/img/13.jpg',
      price: 90,
      brand: ' FORTUNE',
      rating: 4.7,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '14',
      name: 'TOOTHPASTE',
      category: 'TOOTHPASTE',
      image: '/img/22.jpg',
      price: 50,
      brand: ' HIMALYA',
      rating: 4.8,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '15',
      name: 'TOOTHPASTE',
      category: 'TOOTHPASTE',
      image: '/img/21.jpg',
      price: 60,
      brand: ' COLGATE',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '16',
      name: 'SUNFLOWER OIL',
      category: 'OIL',
      image: '/img/16.jpg',
      price: 50,
      brand: ' Dalda',
      rating: 4.3,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '17',
      name: 'AASHIRWAD ATTA',
      category: 'FLOOR',
      image: '/img/17.jpg',
      price: 170,
      brand: ' AASHIRWAD',
      rating: 5.0,
      numReviews: 20,
      countInStock: 6,
    }, {
      _id: '18',
      name: 'PARIVAR KING ATTA',
      category: 'FLOOR',
      image: '/img/18.jpg',
      price: 150,
      brand: ' PARIWAR KING',
      rating: 3.5,
      numReviews: 4,
      countInStock: 6,
    }, {
      _id: '19',
      name: 'SAPTRISHI ATTA',
      category: 'FLOOR',
      image: '/img/19.jpg',
      price: 70,
      brand: ' SAPTRISHI',
      rating: 2,
      numReviews: 5,
      countInStock: 6,
    }, {
      _id: '20',
      name: 'PATANJALI ATTA',
      category: 'FLOOR',
      image: '/img/20.jpg',
      price: 130,
      brand: ' PATANJALI',
      rating: 5,
      numReviews: 15,
      countInStock: 6,
    },{
      _id: '21',
      name: 'PEPSODENT WHITE',
      category: 'TOOTHPASTE',
      image: '/img/23.jpg',
      price: 70,
      brand: ' PEPSODENT',
      rating: 4.6,
      numReviews: 10,
      countInStock: 6,
    },
  ]
}